# Generated by Django 5.1.7 on 2025-03-22 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
